<?php

/**
 * Implement autoload with composer
 * 
 * Usage:
 *  - composer dumpautoload
 *  - php index.php
 */

// Step 1: We must require autoload file generated by composer
require_once 'vendor/autoload.php';

// Step 2: Now, we can use a class with namespace
use App\User;

// Step 3: Create an instance of a class
$user = new User();